#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy

sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sed -i -e '$a\listen balancer\n\tbind :80\n\tbalance roundrobin\n\tserver 6151-web-01 50.19.15.223 check\n\tserver 6151-web-02 54.226.4.36 check\n' /etc/haproxy/haproxy.cfg
service haproxy restart