#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

apt-get -y update
apt-get -y install nginx
echo 'Holberton School' > /usr/share/nginx/html/index.html
service nginx start
