#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# redirects to another page
# Have a custom 404 page

ADD301_REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"
ADD404_NOTFOUND="error_page 404 /custom_404.html;\n\\tlocation = /custom_404.html {\n\t\t root /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
PATTERN="#error_page 404 /404.html;"

apt-get update
apt-get -y install nginx
service nginx start

echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sed -i "30i $ADD301_REDIRECT" /usr/share/nginx/html/index.html #add at line 30

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sed -i "s@$PATTERN@$ADD404_NOTFOUND@" /usr/share/nginx/html/index.html #uncomment and replace

service nginx restart